# Generated by Django 4.2.7 on 2023-12-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('photo', models.ImageField(upload_to='newsapp/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('add_category', models.ManyToManyField(blank=True, related_name='add', to='newsapp.category')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='newsapp.category')),
            ],
        ),
    ]
